- hosts: localhost
  connection: local
  vars:
    region: "us-east-1"
    ec2_id: "ami-22ce4934"
    key_pair: "pythian-markwardt"
  tasks:
    - name: "Get Public Subnet ID"
      ec2_vpc_subnet_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": markwardt-public
      register: markwardt_public

    - name: Subnet ID
      debug:
        var: markwardt_public['subnets'][0]['id']

    - name: Get web SG ID
      ec2_group_facts:
        region: "{{ region }}"
        filters:
          group-name: markwardt-web
      register: web_sg

    - name: Web SG ID
      debug:
        var: web_sg['security_groups'][0]['group_id']    

    - name: Get bastion SG ID
      ec2_group_facts:
        region: "{{ region }}"
        filters:
          group-name: markwardt-bastion
      register: bastion_sg

    - name: Bastion SG ID
      debug:
        var: bastion_sg['security_groups'][0]['group_id']

    - name: Create Bastion
      ec2:
        region: "{{ region }}"
        key_name: "{{ key_pair }}"
        group_id: "{{ bastion_sg['security_groups'][0]['group_id'] }}"
        instance_type: t2.micro
        image: "{{ ec2_id }}"
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
          Name: markwardt-bastion
        vpc_subnet_id: "{{ markwardt_public['subnets'][0]['id'] }}"
        assign_public_ip: yes
    - name: Create Web
      ec2:
        region: "{{ region }}"
        key_name: "{{ key_pair }}"
        group_id: "{{ web_sg['security_groups'][0]['group_id'] }}"
        instance_type: t2.micro
        image: "{{ ec2_id }}"
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
          Name: markwardt-web
        vpc_subnet_id: "{{ markwardt_public['subnets'][0]['id'] }}"
        assign_public_ip: yes
        
    
   