- hosts: localhost
  connection: local
  vars:
    region: "us-east-1"
  
  gather_facts: False
  tasks:
    - name: Get VPC ID
      ec2_vpc_net_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": markwardt-vpc
      register: vpc_facts

    - name: Destroy SG MySQL
      ec2_group:
        name: markwardt-private
        state: absent
        region: "{{ region }}"

    - name: Destroy SG Web
      ec2_group:
        name: markwardt-web
        state: absent
        region: "{{ region }}"

    - name: Destroy SG Bastion
      ec2_group:
        name: markwardt-bastion
        state: absent
        region: "{{ region }}"

    - name: Remove subnet route table
      ec2_vpc_route_table:
        region: "{{ region }}"
        state: absent
        tags:
          Name: markwardt-public
        vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"   
        
    - name: Remove Public Subnet 
      ec2_vpc_subnet:
        state: absent
        cidr: 10.4.0.0/24
        region: "{{ region }}"
        vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"

    - name: Remove Private Subnet 1
      ec2_vpc_subnet:
        state: absent
        cidr: 10.4.1.0/24
        region: "{{ region }}"
        vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"

    - name: Remove Private Subnet 2
      ec2_vpc_subnet:
        state: absent
        cidr: 10.4.2.0/24
        region: "{{ region }}"
        vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"

    - name: Create internet gateway    
      ec2_vpc_igw:
        vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"
        state: absent
        region: "{{ region }}"

    - name: Remove VPC
      ec2_vpc_net:
        name: "markwardt-vpc"
        state: absent
        cidr_block: 10.4.0.0/16
        region: "{{ region }}"
 
  
    