- hosts: localhost
  connection: local
  vars:
    region: "us-east-1"
    rds_name: markwardt-rds
  tasks:
    - name: Remove RDS Instance
      rds:
        region: "{{ region }}"
        command: delete
        instance_name: "{{ rds_name }}"