- hosts: localhost
  connection: local
  vars:
    region: "us-east-1"
    subnet_group_name: markwardt-subnetgroup
  tasks:
    - name: "Get Subnet ID for markwardt-private1"
      ec2_vpc_subnet_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": markwardt-private1
      register: subnet_private1
    
    - name: "Get Subnet ID for markwardt-private2"
      ec2_vpc_subnet_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": markwardt-private2
      register: subnet_private2

    - name: Get MySQL SG ID
      ec2_group_facts:
        region: "{{ region }}"
        filters:
          group-name: markwardt-private
      register: private_sg

    - name: Build RDS Subnet Group
      rds_subnet_group:
        region: "{{ region }}"
        state: present
        name: "{{ subnet_group_name }}"
        description: Subnet Group for Markwardt Testing
        subnets:
          - "{{ subnet_private1['subnets'][0]['id'] }}"
          - "{{ subnet_private2['subnets'][0]['id'] }}"
      register: subnet_group_results

    - name: Subnet group results
      debug:
        var: subnet_group_results

    - name: Build RDS Instance
      rds:
        command: create
        instance_name: markwardt-rds
        db_engine: MySQL
        size: 10
        instance_type: db.m1.small
        username: root
        password: pythian1
        region: "{{ region }}"
        subnet: "{{ subnet_group_name }}"
        vpc_security_groups: "{{ private_sg['security_groups'][0]['group_id'] }}"
        multi_zone: yes
        tags:
          Environment: testing
          Application: ansible
      register: rds_results

    - name: RDS rds results
      debug:
        var: rds_results