- hosts: localhost
  connection: local
  vars:
    region: "us-east-1"
    aws_network_name: markwardt
  tasks:
    - name: Remove RDS Instance
      rds:
        region: "{{ region }}"
        command: delete
        instance_name: "{{ aws_network_name }}-rds"
        wait: yes
        wait_timeout: 1200
    - name: Remove RDS Subnet Group
      rds_subnet_group:
        region: "{{ region }}"
        state: absent
        name: "{{ aws_network_name }}-subnetgroup"